window.MRGLang = {
  vi: {
    brand: "MRGWallet",
    badge_live: "trực tiếp",
    badge_mock: "mẫu",
    badge_mock_fallback: "mẫu-dự phòng",
    addr_title: "Địa chỉ MRG của bạn",
    addr_copy: "Sao chép",
    addr_copied: "Đã sao chép",
    addr_copy_failed: "Sao chép thất bại",
    addr_scan: "Mở Scan",
    addr_note: "Vault mẫu theo mặc định. Sản phẩm sử dụng Solana SPL MRG + bằng chứng sổ cái MergeOS.",
    token_title: "Kinh tế token",
    ledger_title: "Mẹo sổ cái",
    solana_title: "Liên kết Solana",
    bounty_title: "Tiền thưởng có thể nhận",
    bounty_refresh: "Làm mới",
    bounty_none: "Không có tiền thưởng nào",
    receipt_title: "Biên nhận yêu cầu",
    receipt_note: "Liên kết địa chỉ ví với mẹo sổ cái. Thanh toán cần admin chấp nhận / Solana releasePayout.",
    settings_title: "Cài đặt",
    worker_label: "ID công nhân",
    worker_placeholder: "github:tên-của-bạn",
    worker_muted: "Được sử dụng trong biên nhận yêu cầu để xác định công nhân. Đã lưu vào localStorage.",
    generated: "Đã tạo",
    symbol: "Ký hiệu",
    minted: "Đã phát hành",
    reserve: "Dự trữ",
    released: "Đã giải phóng",
    entries: "Bản ghi",
    server_valid: "Máy chủ hợp lệ",
    verified: "Đã xác minh",
    broken: "Hỏng",
    tip: "Mẹo",
    ledger_ref: "Tham chiếu sổ cái",
    program: "Chương trình",
    program_id: "ID chương trình",
    chain: "Chuỗi",
    status: "Trạng thái",
    release_ix: "Lệnh giải phóng",
    lang_label: "Ngôn ngữ",
    lang_en: "English",
    lang_vi: "Tiếng Việt",
    footer_shop: "mergeos.shop",
    footer_scan: "quét",
  },
};
